# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog Why R - ogólnopolskiej konferencji użytkowników R
email: whyr@mini.pw.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Ogólnopolska konferencja użytkowników R to spotkanie entuzjastów pakietu statystycznego R, zarówno z biznesu jak i środowiska akademickiego. To wydarzenie jest niepowtarzalną okazją na powiększenie wiedzy o R, udoskonalenie umiejętności analitycznych i programistycznych a także na poszerzenie kontaktów w polskim środowisku R
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whyr.pl" # the base hostname & protocol for your site
twitter_username: whyRconf
github_username:  whyR-conference
facebook_username: wwhyRconf

encoding: utf-8

# Build settings
markdown: kramdown
